### ISSUE TITLE
make analysis doesn't work

### ISSUE THREAD

**Issue by rossbar** [berkeley-stat159/project-epsilon#315]
Your targets for the analysis (all-analysis, and the individual analyses themselves) don't work. If you are planning on fixing this, please push the changes soon so we can evaluate the project. If not, apply the _wontfix_ label and we will try to run your code by hand

**Comment by mingujo** [comment]
@rossbar @soazig  please give us a second, we'll fix them now

**Comment by soazig** [comment]
Hello @rossbar 

It seems like one of our plotting function got lost between the updates, I am uploading it now.
However, if this is not to much to ask, where you able to download the data ?
Thank you

@mingujo

**Comment by rossbar** [comment]
Yes I was able to successfully download the data (though not from the Makefile in the top-level project directory, I had to use the one in the data/ directory). Thanks for taking a look!

**Comment by soazig** [comment]
Thank you @Ross,
Yes, we realized we forgot to add 'data' in the .PHONY which is why it was
saying that was already up to date.
Thanks !

**Comment by mingujo** [comment]
@rossbar we're running into couple issues so can you give us some couple of minutes to fix and comment when we're done?

**Comment by rossbar** [comment]
That's fine, you don't have to get it done immediately, although the sooner the better. I just posted a piazza announcement about this as many groups had build problems. Just notify me when you are done with these modifications and have verified a successful build from scratch on at least one system (or apply the "wontfix" tag, though it sounds like you're working through the issues)

**Comment by mingujo** [comment]
@rossbar 

Actually, we fixed the bug. Navigation from the original repo should be fine now. 

However, just to make a notice, 'make glm' and 'make multi-comparison' will run for long time. 
For multi-comparison, it will run about an hour

**Comment by rossbar** [comment]
Thanks for the heads-up, long runtimes are okay, but that's why I want to verify that the analysis will run without any errors so that I don't have to keep rerunning a very long analysis only to have it fail multiple times. I will pull and attempt to rerun `make all-analysis`

**Comment by rossbar** [comment]
Still getting IOErrors from `make eda`. Let me know when you have verified a successful run of `make all-analysis` from a fresh clone

**Comment by soazig** [comment]
Hello Ross,
I used a fresh clone and ran into error too.
I have a final at 8am tomorrow, so if that's ok, I'll take a look in the
morning after my final.

Thank you,

On Tue, Dec 15, 2015 at 11:58 PM, Ross Barnowski notifications@github.com
wrote:

> Still getting IOErrors from make eda. Let me know when you have verified
> a successful run of make all-analysis from a fresh clone
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/berkeley-stat159/project-epsilon/issues/315#issuecomment-165026431
> .

## 

Soazig Kaam
PhD student | UC Berkeley College of Environmental Design
http://ced.berkeley.edu/
Graduate Student Researcher | Center for the Built Environment (CBE)
http://www.cbe.berkeley.edu/

**Comment by rossbar** [comment]
Yes definitely,  good luck on your final!

**Comment by ross** [comment]
> Thank you @Ross,

Don't think I'm the Ross you were looking for. Apparently you wanted the other Ross in Berkeley, CA :smile:

**Comment by rossbar** [comment]
Any luck on this guys? I'd like to re-run the analysis ASAP so I can grade the project. Hope all is well with regards to finals and other projects! Let me know how much more time you think you'll need.

**Comment by soazig** [comment]
Hello @rossbar Ross,

Sorry, I think I was able to debug a couple of things.
1. The data type was the most critical, I made sure all data were in float
type.
1. Some of our code were still running with a limited number of subjects
   instead of the entire list.
2. I also added some verbose to know where we are in the code.
3. I changed the README and Makefile to distinguish the analysis for 2
   subjects than for the entire subject list.
4. My tests, coverage and run were successful for the 'make analysis except
   multi". I am finishing up the multi comparison thing.
5. As I am running on the stats department server, I am only able to test
   the multi comparison scripts on 2 subjects. So far so good.

I will update asap, thank you for understanding !

**Comment by soazig** [comment]
Hello @rossbar 

Hopefully the master works now.
​ I have a couple of things to add.
- There was an error in the .bh  script to download the filtered data, you
  only got subject​s​ 1 and 5. I added a new entry in the Makefile in order to download only the
  filtered data. From the main project-epsilon directory, please do `make
  filtered_data_only`. ​ I added a note for you in the README.
- I also separated the fast analysis involving only subject 1 and 5 from
  the longer analysis that compare​s all subjects.
  I updated the README in consequence.
- There are now 2 steps to make the full analysis, To make all
  analyses make `analysis-except-multi` and then `make multi-comparison`
  ​ (see README)​

I hope this makes sense, I am sorry about the confusion
​ and delay​

Thank you!
Soazig

**Comment by soazig** [comment]
Hello @rossbar 
I don't know if you saw my messages above.
Thank you.

**Comment by rossbar** [comment]
Yup, I got them. Just finished successfully running all the analysis :+1:

**Comment by soazig** [comment]
OMG, really ??
I am sorry, it has been a very long week and I was very worried it would not work.
Thank you very much for your time and for being understanding !

**Comment by soazig** [comment]
Sorry I closed the issue

**Comment by rossbar** [comment]
There was one remaining syntax error in the multicomparison part but that was a very simple fix

**Comment by soazig** [comment]
Oh, ok, thank you !
